onboarding = false

[terminal]
default_shell = "/bin/zsh"
shell_mode = "login"
new_cwd = "follow"

[keys]
prefix = "ctrl+b"
remote_image_paste = "cmd+v"

next_workspace = "prefix+shift+j"
previous_workspace = "prefix+shift+k"
switch_workspace = "prefix+shift+1..9"
next_agent = "prefix+a"
previous_agent = "prefix+shift+a"
focus_agent = "prefix+alt+1..9"

goto = "prefix+s"
settings = "prefix+g"
toggle_sidebar = "prefix+b"

[ui]
prompt_new_tab_name = false
copy_on_select = true
tab_bar_position = "top"
agent_panel_sort = "spaces"

show_agent_labels_on_pane_borders = true

[ui.sidebar.agents]
rows = [
  [
    { token = "state_icon" },
    { token = "workspace", bold = false },
    { token = "tab", bold = false },
  ],
  [{ token = "agent", bold = false }],
]

[ui.sidebar.spaces]
rows = [
  [
    { token = "state_icon" },
    { token = "$icon" },
    { token = "workspace", bold = false },
  ],
  [
    { token = "branch", bold = false },
    { token = "git_status", bold = false },
  ],
]

[ui.toast]
delivery = "herdr"

[ui.sound]
enabled = true

[theme]
auto_switch = false
name = "nord"

[theme.custom]
panel_bg = "#0d1117"
surface0 = "#161b22"
surface1 = "#21262d"
surface_dim = "#010409"
overlay0 = "#30363d"
overlay1 = "#484f58"
text = "#e6edf3"
subtext0 = "#848d97"
accent = "#2f81f7"
blue = "#2f81f7"
mauve = "#a371f7"
green = "#3fb950"
yellow = "#d29922"
red = "#f85149"
teal = "#39c5cf"
peach = "#db6d28"

[experimental]
allow_nested = false
