[general]
live_config_reload = true
import = ["~/.config/alacritty/dark.toml"]

[window]
startup_mode = "Maximized"
decorations = "None"
padding = { x = 1, y = 1 }
dynamic_padding = true
option_as_alt = "Both"
dynamic_title = true

[font]
normal = { family = "Ioskeley Mono Term", style = "SemiLight" }
bold = { family = "Ioskeley Mono Term", style = "Regular" }
italic = { family = "Ioskeley Mono Term", style = "SemiLight Italic" }
bold_italic = { family = "Ioskeley Mono Term", style = "Italic" }
size = 14
offset = { x = 0, y = 0 }

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[bell]
duration = 0

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [{ key = "K", mods = "Command", chars = "\u000c" }]
