[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = false
opacity = 0.95
padding = { x = 0, y = 0 }
option_as_alt = "Both"
dimensions = { columns = 160, lines = 80 }
blur = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
size = 13
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "DankMono Nerd Font", style = "Italic" }
bold_italic = { family = "DankMono Nerd Font", style = "Italic" }

[colors.primary]
background = "#212121"
foreground = "#d8dee9"

[colors.cursor]
cursor = "#ebcb8b"
text = "#b89858"

[colors.selection]
background = "#d8dee9"
text = "#212121"

[colors.normal]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"

[colors.bright]
black = "#4c566a"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"
