brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

brew "neovim"

brew "vtsls"
brew "gopls"
brew "rust-analyzer"
brew "yaml-language-server"
brew "vscode-langservers-extracted"
brew "prettier"
brew "gofumpt"
brew "shfmt"
brew "stylua"
brew "taplo"
brew "lua-language-server"
brew "bash-language-server"
brew "shellcheck"
brew "golangci-lint"
brew "tree-sitter-cli"

brew "fzf"
brew "fd"
brew "bat"
brew "ripgrep"
brew "jq"
brew "duti"
brew "git"
brew "gh"
brew "git-delta"

brew "libpq"
brew "pgcli"
brew "redis"
brew "unixodbc"
brew "mise"

brew "cocoapods"
brew "watchman"
brew "delve"

brew "yt-dlp"
brew "ffmpeg"
brew "btop"
brew "fastfetch"

cask "visual-studio-code"
cask "datagrip"
cask "postman"
cask "maccy"
cask "hammerspoon"
cask "google-chrome"
cask "docker-desktop"

cask "aws-vpn-client"

cask "claude-code@latest"
cask "claude"
cask "chatgpt"
cask "codex"

cask "cap"

cask "slack"
cask "discord"
cask "telegram"
cask "ledger-wallet"
