#!/usr/bin/env bash

set -euo pipefail

[[ "$(uname -s)" == "Darwin" ]] || {
  echo "This setup is only supported on macOS."
  exit 1
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="${SCRIPT_DIR}"

BREW_BIN="${BREW_BIN:-$(command -v brew || true)}"
SKIP_BREW=false

while [[ $# -gt 0 ]]; do
  case "$1" in
  --skipBrew)
    SKIP_BREW=true
    shift
    ;;
  *)
    echo "Unknown option: $1"
    echo "Usage: $0 [--skipBrew]"
    exit 1
    ;;
  esac
done

ensure_brew() {
  [[ -n "${BREW_BIN}" ]] && return
  echo "Homebrew not found; installing..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  if [[ -x "/opt/homebrew/bin/brew" ]]; then
    BREW_BIN="/opt/homebrew/bin/brew"
  elif [[ -x "/usr/local/bin/brew" ]]; then
    BREW_BIN="/usr/local/bin/brew"
  else
    echo "Homebrew installation failed: brew not found on PATH."
    exit 1
  fi
}

link_file() {
  local src="$1" dst="$2"
  mkdir -p "$(dirname "${dst}")"
  if [[ -e "${dst}" && ! -L "${dst}" ]]; then
    local backup
    backup="${dst}.bak.$(date +%Y%m%d-%H%M%S)"
    mv "${dst}" "${backup}"
    echo "  backed up ${dst} → ${backup}"
  fi
  ln -sfn "${src}" "${dst}"
}

if [[ -n "${BREW_BIN}" ]]; then
  eval "$("${BREW_BIN}" shellenv)"
elif [[ "${SKIP_BREW}" == false ]]; then
  ensure_brew
  eval "$("${BREW_BIN}" shellenv)"
fi

if [[ "${SKIP_BREW}" == false ]]; then
  echo "Installing Homebrew packages..."
  "${BREW_BIN}" update

  echo "Applying Brewfile..."
  "${BREW_BIN}" bundle --file="${CONFIG_DIR}/Brewfile"
else
  echo "Skipping Homebrew setup (--skipBrew); only linking configuration."
fi

echo "Configuring git..."
link_file "${CONFIG_DIR}/git/gitconfig" "${HOME}/.gitconfig"
link_file "${CONFIG_DIR}/git/ignore" "${HOME}/.config/git/ignore"
link_file "${CONFIG_DIR}/git/allowed_signers" "${HOME}/.config/git/allowed_signers"

SSH_KEY="${HOME}/.ssh/id_ed25519"
SSH_PUB="${SSH_KEY}.pub"

if [[ ! -f "${SSH_KEY}" ]]; then
  echo "Generating SSH key (ed25519)..."
  mkdir -p "${HOME}/.ssh" && chmod 700 "${HOME}/.ssh"
  ssh-keygen -t ed25519 -C "$(git config --get user.email)" -f "${SSH_KEY}" -N ""

  if command -v pbcopy >/dev/null 2>&1; then
    pbcopy <"${SSH_PUB}"
    echo "  ✓ SSH pubkey copied to clipboard."
    echo "  → Add it at https://github.com/settings/ssh/new (auth + signing)"
  fi
fi

# Deliberately OUTSIDE the block above: on a machine where the key already
# exists this still has to run. The marker avoids duplicating the entry.
mkdir -p "${HOME}/.ssh" && chmod 700 "${HOME}/.ssh"
# Matched against a sentinel this block owns, not against `UseKeychain yes`:
# that string is legal inside any per-host block, so grepping the whole file
# reports success while the `Host *` defaults were never written.
SSH_MARKER="# managed by dotfiles"
if ! grep -qF "${SSH_MARKER}" "${HOME}/.ssh/config" 2>/dev/null; then
  echo "Configuring ~/.ssh/config (agent + Keychain)..."
  cat >>"${HOME}/.ssh/config" <<'EOF'

# managed by dotfiles
Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
EOF
  chmod 600 "${HOME}/.ssh/config"
fi
ssh-add --apple-use-keychain "${SSH_KEY}" 2>/dev/null || true

if command -v gh >/dev/null 2>&1 && ! gh auth status >/dev/null 2>&1; then
  echo "  → Run 'gh auth login' to authenticate with GitHub."
fi

echo "Preparing Go workspace..."
mkdir -p "${HOME}/Develop/go/bin"

echo "Linking config files..."
# zsh has no single config directory to link: .zshenv and .zshrc are read from
# $HOME by name. Only the autoloaded functions and the prompt live under
# ~/.config/zsh.
link_file "${CONFIG_DIR}/zsh/zshenv" "${HOME}/.zshenv"
link_file "${CONFIG_DIR}/zsh/zshrc" "${HOME}/.zshrc"
link_file "${CONFIG_DIR}/zsh/functions" "${HOME}/.config/zsh/functions"
link_file "${CONFIG_DIR}/zsh/prompt.zsh" "${HOME}/.config/zsh/prompt.zsh"
link_file "${CONFIG_DIR}/nvim" "${HOME}/.config/nvim"
link_file "${CONFIG_DIR}/mise/config.toml" "${HOME}/.config/mise/config.toml"
# alacritty.toml is generated by `mate`, not linked: live_config_reload never
# fires on a symlinked config, so the file Alacritty opens has to be real.
if [[ -L "${HOME}/.config/alacritty/alacritty.toml" ]]; then
  rm -f "${HOME}/.config/alacritty/alacritty.toml"
fi
# Dark is Alacritty's own default, which is the absence of an import. Only the
# light palette is a file, so only it gets linked.
link_file "${CONFIG_DIR}/alacritty/light.toml" "${HOME}/.config/alacritty/light.toml"
# Same for herdr, where a link would also point `mate`'s output at its input.
if [[ -L "${HOME}/.config/herdr/config.toml" ]]; then
  rm -f "${HOME}/.config/herdr/config.toml"
fi
# `mate` toggles light/dark by hand.
link_file "${CONFIG_DIR}/bin/mate" "${HOME}/.local/bin/mate"
# Seeds alacritty.toml and herdr's config.toml.
"${CONFIG_DIR}/bin/mate" auto >/dev/null
# herdr resolves these from its config file's directory.
link_file "${CONFIG_DIR}/herdr/sounds/done.mp3" "${HOME}/.config/herdr/sounds/done.mp3"
link_file "${CONFIG_DIR}/herdr/sounds/request.mp3" "${HOME}/.config/herdr/sounds/request.mp3"
# btop rewrites this file on exit, comments and all, so the reason it is here
# cannot live inside it: color_theme = "TTY" makes btop draw from the terminal's
# sixteen ANSI slots instead of a theme file of its own, which is what keeps it
# following Alacritty's own default palette for free. Expect btop to churn the
# file whenever a setting is changed from its UI.
link_file "${CONFIG_DIR}/btop/btop.conf" "${HOME}/.config/btop/btop.conf"
# The XDG path, which tmux has read since 3.1, and not ~/.tmux.conf — still
# honoured, but only as a fallback and only when this file is absent. An older
# ~/.tmux.conf left over from a previous machine is not touched by this and
# silently stops being read, which is the confusing half of the move.
link_file "${CONFIG_DIR}/tmux/tmux.conf" "${HOME}/.config/tmux/tmux.conf"
# history-file is dropped silently without this directory, and tmux does not
# create it.
mkdir -p "${HOME}/.local/state/zsh" "${HOME}/.cache/zsh"
mkdir -p "${HOME}/.local/state/tmux"
# init.lua and the mate/ directory it requires, but never ~/.hammerspoon itself:
# Spoons lives there and is downloaded state, not config. Hammerspoon's
# package.path already covers ~/.hammerspoon/?.lua, so the symlinked directory
# is enough for require("mate.frame") to resolve.
link_file "${CONFIG_DIR}/hammerspoon/init.lua" "${HOME}/.hammerspoon/init.lua"
link_file "${CONFIG_DIR}/hammerspoon/mate" "${HOME}/.hammerspoon/mate"
# REDISCLI_HISTFILE points inside this one, and redis-cli won't mkdir.
mkdir -p "${HOME}/.local/state/redis"
if [[ -f "${CONFIG_DIR}/gh/config.yml" ]]; then
  link_file "${CONFIG_DIR}/gh/config.yml" "${HOME}/.config/gh/config.yml"
fi

if [[ "${SKIP_BREW}" == false ]] && command -v mise >/dev/null 2>&1; then
  echo "Installing mise-managed tools..."
  mise install
fi

# No terminal font here, and none in the Brewfile either: the font-ioskeley-mono
# cask ships only the Normal build, with no Term cut. It is a manual install, see
# the README; the face is named in alacritty/alacritty.toml.

echo "Applying macOS defaults..."
defaults write NSGlobalDomain InitialKeyRepeat -int 15
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
defaults write com.apple.finder AppleShowAllExtensions -bool true
defaults write com.apple.finder AppleShowAllFiles -bool true
defaults write NSGlobalDomain AppleShowAllExtensions -bool true
mkdir -p "${HOME}/Screenshots"
defaults write com.apple.screencapture location "${HOME}/Screenshots"
defaults write com.apple.screencapture type -string "png"
if command -v duti >/dev/null 2>&1; then
  duti -s com.microsoft.VSCode public.json all
  duti -s com.microsoft.VSCode public.yaml all
  for ext in toml ini cfg; do
    duti -s com.microsoft.VSCode ".${ext}" all
  done
  # No browser line here on purpose. macOS 27 ignores duti for http/https —
  # error -50 on the schemes, silence on public.html — because only the browser
  # itself may ask for the handler. hammerspoon/mate/browser.lua checks it on
  # every load and says so when it is wrong; setting it is a click.
fi
killall Finder 2>/dev/null || true
killall SystemUIServer 2>/dev/null || true

# /bin/zsh is in /etc/shells out of the box on macOS, so unlike the fish setup
# this needs no sudo. dscl reads the real login shell, not $SHELL.
SHELL_BIN=/bin/zsh
LOGIN_SHELL="$(dscl . -read "/Users/${USER}" UserShell 2>/dev/null | awk '{print $2}')"
if [[ "${LOGIN_SHELL}" != "${SHELL_BIN}" ]]; then
  echo "Changing login shell to ${SHELL_BIN} (chsh will prompt for your password)..."
  chsh -s "${SHELL_BIN}" || echo "chsh needs an interactive password; run it yourself."
fi

echo "macOS standalone setup complete. Happy Coding 🧉"
