return function(c, _)
  return {
    -- Signs in debugger.lua use Diagnostic* as texthl; the stopped line gets
    -- its own tint so it is not mistaken for a selection.
    DapStoppedLine = { bg = c.diff_add },
    DapBreakpoint = { fg = c.error },
    DapBreakpointCondition = { fg = c.warning },
    DapBreakpointRejected = { fg = c.grey },
    DapLogPoint = { fg = c.info },
    DapStopped = { fg = c.ok },

    DapUINormal = { fg = c.fg, bg = c.bg_alt },
    DapUINormalNC = { fg = c.fg, bg = c.bg_alt },
    DapUIEndOfBuffer = { fg = c.bg_alt, bg = c.bg_alt },
    DapUIFloatNormal = { fg = c.fg, bg = c.bg_alt },
    DapUIFloatBorder = { fg = c.border, bg = c.bg_alt },
    DapUIWinSelect = { fg = c.keyword, bold = true },
    DapUIVariable = { fg = c.fg },
    DapUIScope = { fg = c.func, bold = true },
    DapUIType = { fg = c.type },
    DapUIValue = { fg = c.fg },
    DapUIModifiedValue = { fg = c.warning, bold = true },
    DapUIDecoration = { fg = c.grey },
    DapUIThread = { fg = c.ok },
    DapUIStoppedThread = { fg = c.keyword, bold = true },
    DapUIFrameName = { fg = c.fg },
    DapUICurrentFrameName = { fg = c.keyword, bold = true },
    DapUISource = { fg = c.teal },
    DapUILineNumber = { fg = c.grey },
    DapUIWatchesEmpty = { fg = c.comment },
    DapUIWatchesValue = { fg = c.ok },
    DapUIWatchesError = { fg = c.error },
    DapUIBreakpointsPath = { fg = c.func },
    DapUIBreakpointsInfo = { fg = c.ok },
    DapUIBreakpointsCurrentLine = { fg = c.keyword, bold = true },
    DapUIBreakpointsLine = { fg = c.grey },
    DapUIBreakpointsDisabledLine = { fg = c.comment },
    DapUIStepOver = { fg = c.func },
    DapUIStepInto = { fg = c.func },
    DapUIStepBack = { fg = c.func },
    DapUIStepOut = { fg = c.func },
    DapUIStop = { fg = c.error },
    DapUIPlayPause = { fg = c.ok },
    DapUIRestart = { fg = c.ok },
    DapUIUnavailable = { fg = c.comment },
    DapUIStepOverNC = { fg = c.func, bg = c.bg_alt },
    DapUIStepIntoNC = { fg = c.func, bg = c.bg_alt },
    DapUIStepBackNC = { fg = c.func, bg = c.bg_alt },
    DapUIStepOutNC = { fg = c.func, bg = c.bg_alt },
    DapUIStopNC = { fg = c.error, bg = c.bg_alt },
    DapUIPlayPauseNC = { fg = c.ok, bg = c.bg_alt },
    DapUIRestartNC = { fg = c.ok, bg = c.bg_alt },
    DapUIUnavailableNC = { fg = c.comment, bg = c.bg_alt },

    NvimDapVirtualText = { fg = c.comment, italic = true },
    NvimDapVirtualTextChanged = { fg = c.warning, italic = true },
    NvimDapVirtualTextError = { fg = c.error, italic = true },
    NvimDapVirtualTextInfo = { fg = c.info, italic = true },
  }
end
