return function(c, _)
  return {
    Normal = { fg = c.fg, bg = c.bg },
    NormalNC = { fg = c.fg, bg = c.bg },
    -- Floats are non-flat: one step lighter than the ground, bordered.
    NormalFloat = { fg = c.fg, bg = c.bg_alt },
    FloatBorder = { fg = c.border, bg = c.bg_alt },
    FloatTitle = { fg = c.silver, bg = c.bg_alt, bold = true },
    FloatFooter = { fg = c.grey, bg = c.bg_alt },
    FloatShadow = { bg = c.bg_alt },
    FloatShadowThrough = { bg = c.bg_alt },

    Cursor = { fg = c.bg, bg = c.fg },
    lCursor = { fg = c.bg, bg = c.fg },
    CursorIM = { fg = c.bg, bg = c.fg },
    TermCursor = { fg = c.bg, bg = c.fg },
    TermCursorNC = { fg = c.bg, bg = c.grey },

    CursorLine = { bg = c.bg_soft },
    CursorColumn = { bg = c.bg_soft },
    ColorColumn = { bg = c.bg_soft },
    CursorLineNr = { fg = c.silver, bg = c.bg_soft, bold = true },
    CursorLineSign = { bg = c.bg_soft },
    CursorLineFold = { bg = c.bg_soft },
    LineNr = { fg = c.grey },
    LineNrAbove = { fg = c.grey },
    LineNrBelow = { fg = c.grey },
    SignColumn = { fg = c.comment, bg = c.bg },
    FoldColumn = { fg = c.comment, bg = c.bg },
    Folded = { fg = c.grey_light, bg = c.bg_soft },

    Visual = { bg = c.selection },
    VisualNOS = { bg = c.selection },
    -- Search is a different family from selection on purpose.
    Search = { fg = c.bg, bg = c.warning },
    CurSearch = { fg = c.bg, bg = c.keyword, bold = true },
    IncSearch = { fg = c.bg, bg = c.keyword, bold = true },
    Substitute = { fg = c.bg, bg = c.error },
    MatchParen = { fg = c.keyword, bg = c.surface, bold = true },

    Pmenu = { fg = c.fg, bg = c.surface },
    PmenuSel = { fg = c.fg_bright, bg = c.selection, bold = true },
    PmenuKind = { fg = c.func, bg = c.surface },
    PmenuKindSel = { fg = c.func, bg = c.selection },
    PmenuExtra = { fg = c.grey_light, bg = c.surface },
    PmenuExtraSel = { fg = c.grey_light, bg = c.selection },
    PmenuMatch = { fg = c.keyword, bg = c.surface, bold = true },
    PmenuMatchSel = { fg = c.keyword, bg = c.selection, bold = true },
    PmenuSbar = { bg = c.surface },
    PmenuThumb = { bg = c.border },
    ComplMatchIns = { fg = c.grey_light },
    WildMenu = { fg = c.bg, bg = c.keyword },

    StatusLine = { fg = c.silver, bg = c.bg_alt },
    StatusLineNC = { fg = c.grey, bg = c.bg_soft },
    StatusLineTerm = { fg = c.silver, bg = c.bg_alt },
    StatusLineTermNC = { fg = c.grey, bg = c.bg_soft },
    WinBar = { fg = c.silver, bg = c.bg },
    WinBarNC = { fg = c.grey, bg = c.bg },
    WinSeparator = { fg = c.border, bg = c.bg },
    VertSplit = { fg = c.border, bg = c.bg },
    TabLine = { fg = c.grey, bg = c.bg_alt },
    TabLineFill = { bg = c.bg_alt },
    TabLineSel = { fg = c.fg_bright, bg = c.bg, bold = true },

    MsgArea = { fg = c.fg, bg = c.bg },
    MsgSeparator = { fg = c.border, bg = c.bg },
    ModeMsg = { fg = c.silver, bold = true },
    MoreMsg = { fg = c.func },
    Question = { fg = c.func },
    WarningMsg = { fg = c.warning },
    ErrorMsg = { fg = c.error },
    Title = { fg = c.func, bold = true },
    Directory = { fg = c.func },

    NonText = { fg = c.surface },
    Whitespace = { fg = c.surface },
    SpecialKey = { fg = c.grey },
    EndOfBuffer = { fg = c.bg },
    Conceal = { fg = c.grey },

    QuickFixLine = { bg = c.bg_soft, bold = true },
    qfFileName = { fg = c.func },
    qfLineNr = { fg = c.grey },
    qfSeparator = { fg = c.grey },

    SpellBad = { sp = c.error, undercurl = true },
    SpellCap = { sp = c.warning, undercurl = true },
    SpellLocal = { sp = c.info, undercurl = true },
    SpellRare = { sp = c.type, undercurl = true },

    healthSuccess = { fg = c.bg, bg = c.ok },
    healthWarning = { fg = c.bg, bg = c.warning },
    healthError = { fg = c.bg, bg = c.error },
    healthHelp = { fg = c.func },

    SnippetTabstop = { bg = c.surface },
    RedrawDebugNormal = { reverse = true },
    RedrawDebugClear = { bg = c.warning },
    RedrawDebugComposed = { bg = c.ok },
    RedrawDebugRecompose = { bg = c.error },
  }
end
