return function(c, _)
  return {
    FzfLuaNormal = { fg = c.fg, bg = c.bg_alt },
    FzfLuaBorder = { fg = c.border, bg = c.bg_alt },
    FzfLuaTitle = { fg = c.silver, bg = c.bg_alt, bold = true },
    FzfLuaTitleFlags = { fg = c.bg, bg = c.keyword },
    FzfLuaBackdrop = { bg = c.bg },
    FzfLuaPreviewNormal = { fg = c.fg, bg = c.bg },
    FzfLuaPreviewBorder = { fg = c.border, bg = c.bg },
    FzfLuaPreviewTitle = { fg = c.silver, bg = c.bg, bold = true },
    FzfLuaCursor = { fg = c.bg, bg = c.fg },
    FzfLuaCursorLine = { bg = c.bg_soft },
    FzfLuaCursorLineNr = { fg = c.silver, bg = c.bg_soft, bold = true },
    FzfLuaSearch = { fg = c.bg, bg = c.warning },
    FzfLuaScrollBorderEmpty = { fg = c.border, bg = c.bg },
    FzfLuaScrollBorderFull = { fg = c.grey, bg = c.bg },
    FzfLuaScrollFloatEmpty = { bg = c.surface },
    FzfLuaScrollFloatFull = { bg = c.grey },
    FzfLuaHelpNormal = { fg = c.fg, bg = c.bg_alt },
    FzfLuaHelpBorder = { fg = c.border, bg = c.bg_alt },
    FzfLuaHeaderBind = { fg = c.keyword },
    FzfLuaHeaderText = { fg = c.grey_light },
    FzfLuaPathColNr = { fg = c.teal },
    FzfLuaPathLineNr = { fg = c.grey },
    FzfLuaBufName = { fg = c.type },
    FzfLuaBufId = { fg = c.grey },
    FzfLuaBufNr = { fg = c.grey },
    FzfLuaBufLineNr = { fg = c.grey },
    FzfLuaBufFlagCur = { fg = c.keyword },
    FzfLuaBufFlagAlt = { fg = c.func },
    FzfLuaTabTitle = { fg = c.type, bold = true },
    FzfLuaTabMarker = { fg = c.keyword, bold = true },
    FzfLuaDirIcon = { fg = c.func },
    FzfLuaDirPart = { fg = c.grey },
    FzfLuaFilePart = { fg = c.fg },
    FzfLuaLiveSym = { fg = c.keyword },
    FzfLuaLivePrompt = { fg = c.keyword },

    -- Read by fzf itself when fzf_colors = true in the setup.
    FzfLuaFzfNormal = { fg = c.fg, bg = c.bg_alt },
    FzfLuaFzfCursorLine = { fg = c.fg_bright, bg = c.bg_soft },
    FzfLuaFzfMatch = { fg = c.keyword, bold = true },
    FzfLuaFzfBorder = { fg = c.border },
    FzfLuaFzfScrollbar = { fg = c.grey },
    FzfLuaFzfSeparator = { fg = c.border },
    FzfLuaFzfGutter = { bg = c.bg_alt },
    FzfLuaFzfHeader = { fg = c.grey_light },
    FzfLuaFzfInfo = { fg = c.comment },
    FzfLuaFzfPointer = { fg = c.keyword },
    FzfLuaFzfMarker = { fg = c.ok },
    FzfLuaFzfSpinner = { fg = c.teal },
    FzfLuaFzfPrompt = { fg = c.func },
    FzfLuaFzfQuery = { fg = c.fg_bright },
  }
end
