return function(c, _)
  return {
    GitSignsAdd = { fg = c.ok, bg = c.bg },
    GitSignsChange = { fg = c.warning, bg = c.bg },
    GitSignsDelete = { fg = c.error, bg = c.bg },
    GitSignsChangedelete = { fg = c.warning, bg = c.bg },
    GitSignsTopdelete = { fg = c.error, bg = c.bg },
    GitSignsUntracked = { fg = c.teal, bg = c.bg },
    GitSignsAddNr = { fg = c.ok },
    GitSignsChangeNr = { fg = c.warning },
    GitSignsDeleteNr = { fg = c.error },
    GitSignsAddLn = { bg = c.diff_add },
    GitSignsChangeLn = { bg = c.diff_change },
    GitSignsDeleteLn = { bg = c.diff_delete },
    GitSignsAddPreview = { bg = c.diff_add },
    GitSignsDeletePreview = { bg = c.diff_delete },
    GitSignsAddInline = { bg = c.diff_text },
    GitSignsChangeInline = { bg = c.diff_text },
    GitSignsDeleteInline = { bg = c.diff_text },
    GitSignsAddLnInline = { bg = c.diff_text },
    GitSignsChangeLnInline = { bg = c.diff_text },
    GitSignsDeleteLnInline = { bg = c.diff_text },
    GitSignsAddVirtLn = { bg = c.diff_add },
    GitSignsChangeVirtLn = { bg = c.diff_change },
    GitSignsDeleteVirtLn = { bg = c.diff_delete },
    GitSignsAddVirtLnInLine = { bg = c.diff_text },
    GitSignsChangeVirtLnInLine = { bg = c.diff_text },
    GitSignsDeleteVirtLnInLine = { bg = c.diff_text },
    GitSignsStagedAdd = { fg = c.string, bg = c.bg },
    GitSignsStagedChange = { fg = c.signal, bg = c.bg },
    GitSignsStagedDelete = { fg = c.hint, bg = c.bg },
    GitSignsStagedChangedelete = { fg = c.signal, bg = c.bg },
    GitSignsStagedTopdelete = { fg = c.hint, bg = c.bg },
    GitSignsStagedUntracked = { fg = c.teal, bg = c.bg },
    GitSignsCurrentLineBlame = { fg = c.comment, italic = true },
    GitSignsDeleteVirtLnPreview = { bg = c.diff_delete },
  }
end
