return function(c, _)
  return {
    NeoTreeNormal = { fg = c.fg, bg = c.bg_alt },
    NeoTreeNormalNC = { fg = c.fg, bg = c.bg_alt },
    NeoTreeEndOfBuffer = { fg = c.bg_alt, bg = c.bg_alt },
    NeoTreeWinSeparator = { fg = c.border, bg = c.bg_alt },
    NeoTreeVertSplit = { fg = c.border, bg = c.bg_alt },
    NeoTreeCursorLine = { bg = c.bg_soft },
    NeoTreeStatusLine = { fg = c.grey, bg = c.bg_alt },
    NeoTreeStatusLineNC = { fg = c.grey, bg = c.bg_alt },
    NeoTreeSignColumn = { bg = c.bg_alt },
    NeoTreeTitleBar = { fg = c.silver, bg = c.bg_alt, bold = true },
    NeoTreeFloatBorder = { fg = c.border, bg = c.bg_alt },
    NeoTreeFloatTitle = { fg = c.silver, bg = c.bg_alt, bold = true },
    NeoTreeFloatNormal = { fg = c.fg, bg = c.bg_alt },

    NeoTreeRootName = { fg = c.silver, bold = true },
    NeoTreeDirectoryName = { fg = c.func },
    NeoTreeDirectoryIcon = { fg = c.func },
    NeoTreeFileName = { fg = c.fg },
    NeoTreeFileIcon = { fg = c.grey_light },
    NeoTreeFileNameOpened = { fg = c.fg_bright, bold = true },
    NeoTreeSymbolicLinkTarget = { fg = c.teal },
    NeoTreeDotfile = { fg = c.grey },
    NeoTreeHiddenByName = { fg = c.grey },
    NeoTreeDimText = { fg = c.comment },
    NeoTreeMessage = { fg = c.comment, italic = true },
    NeoTreeIndentMarker = { fg = c.surface },
    NeoTreeExpander = { fg = c.grey },
    NeoTreeModified = { fg = c.warning },
    NeoTreeBufferNumber = { fg = c.grey },
    NeoTreeFilterTerm = { fg = c.keyword, bold = true },
    NeoTreeFadeText1 = { fg = c.grey },
    NeoTreeFadeText2 = { fg = c.comment },
    NeoTreePreview = { bg = c.bg_soft },
    NeoTreeWindowsHidden = { fg = c.grey },
    NeoTreeTabActive = { fg = c.fg_bright, bg = c.bg, bold = true },
    NeoTreeTabInactive = { fg = c.grey, bg = c.bg_alt },
    NeoTreeTabSeparatorActive = { fg = c.bg, bg = c.bg },
    NeoTreeTabSeparatorInactive = { fg = c.bg_alt, bg = c.bg_alt },

    -- Same order as the letters set in ui.lua.
    NeoTreeGitAdded = { fg = c.ok },
    NeoTreeGitModified = { fg = c.warning },
    NeoTreeGitDeleted = { fg = c.error },
    NeoTreeGitRenamed = { fg = c.type },
    NeoTreeGitUntracked = { fg = c.teal },
    NeoTreeGitConflict = { fg = c.error, bold = true },
    NeoTreeGitStaged = { fg = c.ok },
    NeoTreeGitUnstaged = { fg = c.warning },
    NeoTreeGitIgnored = { fg = c.comment },
  }
end
