return function(c, _)
  return {
    ["@lsp.type.class"] = "@type",
    ["@lsp.type.struct"] = "@type",
    ["@lsp.type.enum"] = "@type",
    ["@lsp.type.interface"] = "@type",
    ["@lsp.type.typeParameter"] = "@type",
    ["@lsp.type.typeAlias"] = "@type.definition",
    ["@lsp.type.builtinType"] = "@type.builtin",
    ["@lsp.type.enumMember"] = "@constant",
    ["@lsp.type.namespace"] = "@module",
    ["@lsp.type.function"] = "@function",
    ["@lsp.type.method"] = "@function.method",
    ["@lsp.type.macro"] = "@function.macro",
    ["@lsp.type.keyword"] = "@keyword",
    ["@lsp.type.operator"] = "@operator",
    ["@lsp.type.number"] = "@number",
    ["@lsp.type.boolean"] = "@boolean",
    ["@lsp.type.comment"] = "@comment",
    ["@lsp.type.parameter"] = "@variable.parameter",
    ["@lsp.type.property"] = "@property",
    ["@lsp.type.decorator"] = "@attribute",
    ["@lsp.type.deriveHelper"] = "@attribute",
    ["@lsp.type.escapeSequence"] = "@string.escape",
    ["@lsp.type.formatSpecifier"] = "@string.special",
    ["@lsp.type.lifetime"] = "@keyword.modifier",
    ["@lsp.type.selfKeyword"] = "@variable.builtin",
    ["@lsp.type.selfTypeKeyword"] = "@variable.builtin",
    ["@lsp.type.event"] = "Special",
    -- Left to treesitter on purpose: strings and plain variables are
    -- better scoped by the query than by the server.
    ["@lsp.type.string"] = {},
    ["@lsp.type.variable"] = {},
    ["@lsp.type.generic"] = {},

    ["@lsp.typemod.class.defaultLibrary"] = "@type.builtin",
    ["@lsp.typemod.enum.defaultLibrary"] = "@type.builtin",
    ["@lsp.typemod.struct.defaultLibrary"] = "@type.builtin",
    ["@lsp.typemod.enumMember.defaultLibrary"] = "@constant.builtin",
    ["@lsp.typemod.function.defaultLibrary"] = "@function.builtin",
    ["@lsp.typemod.method.defaultLibrary"] = "@function.builtin",
    ["@lsp.typemod.macro.defaultLibrary"] = "@function.macro",
    ["@lsp.typemod.variable.defaultLibrary"] = "@variable.builtin",
    ["@lsp.typemod.variable.readonly"] = "@constant",
    ["@lsp.typemod.variable.static"] = "@constant",
    ["@lsp.typemod.variable.callable"] = "@function",
    ["@lsp.typemod.variable.injected"] = "@variable",
    ["@lsp.typemod.property.readonly"] = { fg = c.silver },
    ["@lsp.typemod.keyword.async"] = "@keyword.coroutine",
    ["@lsp.typemod.keyword.injected"] = "@keyword",
    ["@lsp.typemod.operator.injected"] = "@operator",
    ["@lsp.typemod.string.injected"] = "@string",
    ["@lsp.typemod.function.declaration"] = { fg = c.func, bold = true },
    ["@lsp.typemod.method.declaration"] = { fg = c.func, bold = true },
    ["@lsp.mod.deprecated"] = { strikethrough = true },

    -- Kind groups, shared by blink.cmp and anything else that shows a
    -- CompletionItemKind.
    LspKindText = { fg = c.grey_light },
    LspKindMethod = "@function.method",
    LspKindFunction = "@function",
    LspKindConstructor = "@constructor",
    LspKindField = { fg = c.teal },
    LspKindVariable = "@variable",
    LspKindClass = "@type",
    LspKindInterface = "@type",
    LspKindModule = "@module",
    LspKindProperty = { fg = c.teal },
    LspKindUnit = "@constant",
    LspKindValue = "@constant",
    LspKindEnum = "@type",
    LspKindKeyword = "@keyword",
    LspKindSnippet = { fg = c.string },
    LspKindColor = "Special",
    LspKindFile = { fg = c.fg },
    LspKindReference = { fg = c.teal },
    LspKindFolder = "Directory",
    LspKindEnumMember = "@constant",
    LspKindConstant = "@constant",
    LspKindStruct = "@type",
    LspKindEvent = "Special",
    LspKindOperator = "@operator",
    LspKindTypeParameter = "@type",
    LspKindArray = { fg = c.grey },
    LspKindBoolean = "@boolean",
    LspKindKey = { fg = c.teal },
    LspKindNamespace = "@module",
    LspKindNull = "@constant.builtin",
    LspKindNumber = "@number",
    LspKindObject = "@constant",
    LspKindPackage = "@module",
    LspKindString = "@string",
  }
end
