return function(c, opts)
  return {
    Comment = { fg = c.comment, italic = opts.italics.comments },
    Constant = { fg = c.signal },
    String = { fg = c.string },
    Character = { fg = c.string },
    Number = { fg = c.signal },
    Boolean = { fg = c.signal },
    Float = { fg = c.signal },
    Identifier = { fg = c.fg },
    Function = { fg = c.func },
    Statement = { fg = c.keyword },
    Conditional = { fg = c.keyword },
    Repeat = { fg = c.keyword },
    Label = { fg = c.keyword },
    Operator = { fg = c.grey_light },
    Keyword = { fg = c.keyword },
    Exception = { fg = c.keyword },
    PreProc = { fg = c.grey_light },
    Include = { fg = c.grey_light },
    Define = { fg = c.grey_light },
    Macro = { fg = c.keyword },
    PreCondit = { fg = c.grey_light },
    Type = { fg = c.type },
    StorageClass = { fg = c.keyword },
    Structure = { fg = c.type },
    Typedef = { fg = c.type },
    Special = { fg = c.teal },
    SpecialChar = { fg = c.signal },
    Tag = { fg = c.type },
    Delimiter = { fg = c.grey },
    SpecialComment = { fg = c.grey_light, italic = opts.italics.comments },
    Debug = { fg = c.warning },
    Underlined = { underline = true },
    Ignore = { fg = c.grey },
    Error = { fg = c.error },
    Todo = { fg = c.bg, bg = c.info, bold = true },
    Bold = { bold = true },
    Italic = { italic = true },

    Added = { fg = c.ok },
    Changed = { fg = c.warning },
    Removed = { fg = c.error },

    htmlTag = { fg = c.grey },
    htmlEndTag = { fg = c.grey },
    htmlTagName = { fg = c.type },
    htmlArg = { fg = c.teal },
    htmlTitle = { fg = c.fg },
    htmlLink = { fg = c.func, underline = true },
    htmlSpecialChar = { fg = c.signal },

    markdownCode = { fg = c.string },
    markdownCodeBlock = { fg = c.string },
    markdownHeadingDelimiter = { fg = c.grey },
    markdownLinkText = { fg = c.teal },
    markdownUrl = { fg = c.func, underline = true },

    gitcommitSummary = { fg = c.fg, bold = true },
    gitcommitOverflow = { fg = c.error },
    gitcommitHeader = { fg = c.grey_light },
    gitcommitBranch = { fg = c.type },
    gitcommitSelectedFile = { fg = c.ok },
    gitcommitDiscardedFile = { fg = c.error },
    gitcommitUntrackedFile = { fg = c.teal },

    diffAdded = { fg = c.ok },
    diffRemoved = { fg = c.error },
    diffChanged = { fg = c.warning },
    diffFile = { fg = c.func },
    diffIndexLine = { fg = c.grey },
    diffLine = { fg = c.type },
    diffOldFile = { fg = c.error },
    diffNewFile = { fg = c.ok },
  }
end
