return function(c, opts)
  return {
    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.type, italic = true },
    ["@variable.parameter"] = { fg = c.silver },
    ["@variable.parameter.builtin"] = { fg = c.silver, italic = true },
    ["@variable.member"] = { fg = c.fg },

    ["@constant"] = { fg = c.signal },
    ["@constant.builtin"] = { fg = c.signal, bold = true },
    ["@constant.macro"] = { fg = c.keyword },

    ["@module"] = { fg = c.teal },
    ["@module.builtin"] = { fg = c.teal, italic = true },
    ["@label"] = { fg = c.keyword },

    ["@string"] = { fg = c.string },
    ["@string.documentation"] = { fg = c.comment, italic = opts.italics.comments },
    ["@string.regexp"] = { fg = c.teal },
    ["@string.escape"] = { fg = c.signal },
    ["@string.special"] = { fg = c.signal },
    ["@string.special.symbol"] = { fg = c.signal },
    ["@string.special.path"] = { fg = c.string, underline = true },
    ["@string.special.url"] = { fg = c.func, underline = true },
    ["@character"] = { fg = c.string },
    ["@character.special"] = { fg = c.signal },
    ["@character.printf"] = { fg = c.signal },

    ["@boolean"] = { fg = c.signal },
    ["@number"] = { fg = c.signal },
    ["@number.float"] = { fg = c.signal },

    ["@type"] = { fg = c.type },
    ["@type.builtin"] = { fg = c.type, italic = true },
    ["@type.definition"] = { fg = c.type },
    ["@type.qualifier"] = { fg = c.keyword },
    ["@attribute"] = { fg = c.teal },
    ["@attribute.builtin"] = { fg = c.teal, italic = true },
    ["@property"] = { fg = c.fg },

    ["@function"] = { fg = c.func },
    ["@function.builtin"] = { fg = c.func, italic = true },
    ["@function.call"] = { fg = c.func },
    ["@function.macro"] = { fg = c.keyword },
    ["@function.method"] = { fg = c.func },
    ["@function.method.call"] = { fg = c.func },
    ["@constructor"] = { fg = c.type },
    ["@operator"] = { fg = c.grey_light },

    ["@keyword"] = { fg = c.keyword },
    ["@keyword.coroutine"] = { fg = c.keyword },
    ["@keyword.function"] = { fg = c.keyword },
    ["@keyword.operator"] = { fg = c.keyword },
    ["@keyword.import"] = { fg = c.keyword },
    ["@keyword.export"] = { fg = c.keyword },
    ["@keyword.type"] = { fg = c.keyword },
    ["@keyword.modifier"] = { fg = c.keyword },
    ["@keyword.repeat"] = { fg = c.keyword },
    ["@keyword.return"] = { fg = c.keyword },
    ["@keyword.debug"] = { fg = c.warning },
    ["@keyword.exception"] = { fg = c.keyword },
    ["@keyword.conditional"] = { fg = c.keyword },
    ["@keyword.conditional.ternary"] = { fg = c.grey_light },
    ["@keyword.directive"] = { fg = c.grey_light },
    ["@keyword.directive.define"] = { fg = c.grey_light },

    ["@punctuation.delimiter"] = { fg = c.grey },
    ["@punctuation.bracket"] = { fg = c.grey },
    ["@punctuation.special"] = { fg = c.grey_light },

    ["@comment"] = { fg = c.comment, italic = opts.italics.comments },
    ["@comment.documentation"] = { fg = c.comment, italic = opts.italics.comments },
    ["@comment.error"] = { fg = c.bg, bg = c.error, bold = true },
    ["@comment.warning"] = { fg = c.bg, bg = c.warning, bold = true },
    ["@comment.todo"] = { fg = c.bg, bg = c.info, bold = true },
    ["@comment.note"] = { fg = c.bg, bg = c.hint, bold = true },

    ["@markup"] = { fg = c.fg },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = c.func, bold = true },
    ["@markup.heading.1"] = { fg = c.func, bold = true },
    ["@markup.heading.2"] = { fg = c.type, bold = true },
    ["@markup.heading.3"] = { fg = c.keyword, bold = true },
    ["@markup.heading.4"] = { fg = c.string, bold = true },
    ["@markup.heading.5"] = { fg = c.teal, bold = true },
    ["@markup.heading.6"] = { fg = c.grey_light, bold = true },
    ["@markup.quote"] = { fg = c.grey_light, italic = true },
    ["@markup.math"] = { fg = c.teal },
    ["@markup.link"] = { fg = c.teal },
    ["@markup.link.label"] = { fg = c.teal },
    ["@markup.link.url"] = { fg = c.func, underline = true },
    ["@markup.raw"] = { fg = c.string, bg = c.bg_soft },
    ["@markup.raw.block"] = { fg = c.string },
    ["@markup.list"] = { fg = c.grey },
    ["@markup.list.checked"] = { fg = c.ok },
    ["@markup.list.unchecked"] = { fg = c.grey_light },

    ["@diff.plus"] = { fg = c.ok },
    ["@diff.minus"] = { fg = c.error },
    ["@diff.delta"] = { fg = c.warning },

    ["@tag"] = { fg = c.type },
    ["@tag.builtin"] = { fg = c.type },
    ["@tag.attribute"] = { fg = c.teal },
    ["@tag.delimiter"] = { fg = c.grey },

    ["@none"] = {},
    ["@conceal"] = { fg = c.grey },

    -- Per language: only where the generic capture reads wrong.
    ["@property.toml"] = { fg = c.func },
    ["@property.yaml"] = { fg = c.func },
    ["@property.json"] = { fg = c.func },
    ["@label.json"] = { fg = c.func },
    ["@type.builtin.go"] = { fg = c.type },
    ["@variable.builtin.lua"] = { fg = c.type },
    ["@constructor.lua"] = { fg = c.grey },
    ["@punctuation.special.bash"] = { fg = c.signal },
  }
end
