"$schema" = 'https://starship.rs/config-schema.json'
format = '$directory$git_branch$git_state$git_status$line_break$character'
right_format = '$mise$status$cmd_duration$username$hostname$jobs${env_var.STARSHIP_PNPM}$nodejs$bun$golang$rust$python$ruby$terraform$aws$docker_context$time'
add_newline = true
command_timeout = 500
[directory]
style = 'bright-white'
repo_root_style = 'bright-white'
before_repo_root_style = 'bright-white'
truncate_to_repo = false
truncation_length = 0
fish_style_pwd_dir_length = 1
format = '[$path]($style) '
[character]
success_symbol = '[❯](bright-green)'
error_symbol = '[❯](bright-red)'
vimcmd_symbol = '[❮](bright-green)'
vimcmd_replace_symbol = '[▶](bright-purple)'
vimcmd_replace_one_symbol = '[▶](bright-purple)'
vimcmd_visual_symbol = '[V](bright-yellow)'
[git_branch]
symbol = ' '
style = 'green'
format = '[$symbol$branch]($style) '
[git_state]
style = 'red'
format = '\([$state( $progress_current/$progress_total)]($style)\) '
[git_status]
ignore_submodules = true
format = '($all_status$ahead_behind )'
conflicted = '[=${count}](red)'
stashed = '[*${count}](cyan)'
staged = '[+${count}](green)'
modified = '[!${count}](yellow)'
untracked = '[?${count}](purple)'
deleted = '[✘${count}](red)'
renamed = '[»${count}](yellow)'
ahead = '[⇡${count}](cyan)'
behind = '[⇣${count}](cyan)'
diverged = '[⇕⇡${ahead_count}⇣${behind_count}](cyan)'

[mise]
disabled = false
style = 'bright-red'
symbol = ' '
healthy_symbol = ''
unhealthy_symbol = 'mise'
format = '[$symbol$health]($style) '

[status]
disabled = false
style = 'bright-red'
symbol = '✘'
map_symbol = true
recognize_signal_code = true
sigint_symbol = '✘'
signal_symbol = '✘'
not_found_symbol = '✘'
not_executable_symbol = '✘'
pipestatus = true
pipestatus_separator = '[|](bright-black)'
format = '[$symbol$common_meaning$signal_name$maybe_int]($style) '
pipestatus_format = '[$pipestatus]($style)[ => $int]($style) '

[cmd_duration]
min_time = 2000
style = 'bright-cyan'
format = '[󰅐 $duration]($style) '

[username]
show_always = false
style_user = 'bright-black'
style_root = 'bright-red'
format = '[$user]($style)'

[hostname]
ssh_only = true
style = 'red'
format = '[@$hostname]($style) '

[jobs]
symbol = '󰣖 '
style = 'blue'
format = '[$symbol$number]($style) '

[nodejs]
detect_files = ['package.json', '.node-version', '.nvmrc']
symbol = '󰎙 '
style = 'green'
format = '[$symbol($version )]($style)'

[bun]
symbol = ' '
style = 'bright-white'
format = '[$symbol($version )]($style)'

[golang]
symbol = ' '
style = 'bright-cyan'
format = '[$symbol($version )]($style)'

[rust]
symbol = '󱘗 '
style = 'bright-red'
format = '[$symbol($version )]($style)'

[python]
symbol = '󰌠 '
style = 'bright-yellow'
format = '[$symbol($version )(\($virtualenv\) )]($style)'

[ruby]
symbol = '󰴭 '
style = 'red'
format = '[$symbol($version )]($style)'

[terraform]
symbol = '󱁢 '
style = 'bright-purple'
format = '[$symbol$workspace]($style) '

[aws]
symbol = ' '
style = 'yellow'
format = '[$symbol$profile]($style) '

[env_var.STARSHIP_PNPM]
variable = 'STARSHIP_PNPM'
format = '[ ](yellow)'

[docker_context]
only_with_files = false
symbol = '󰡨 '
style = 'bright-cyan'
format = '[$symbol$context]($style) '

[time]
disabled = false
time_format = '%H:%M'
style = 'bright-black'
format = '[$time]($style) '
