-- Generates alacritty/mate.toml from palette.lua and prints herdr's
-- [theme.custom] block. Run from the repo root:
--   nvim -l nvim/lua/mate/build.lua
local here = debug.getinfo(1, "S").source:sub(2)
local root = vim.fs.normalize(vim.fs.dirname(here) .. "/../../..")
package.path = root .. "/nvim/lua/?.lua;" .. root .. "/nvim/lua/?/init.lua;" .. package.path

local p = require("mate.palette")
local c, ansi, idx = p.colors, p.ansi, p.indexed

local names = { "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white" }

local out = {}
local function line(s)
  out[#out + 1] = s
end

line(('# name = "%s"'):format(p.name))
line(('# author = "%s"'):format(p.author))
line("# Generated by nvim/lua/mate/build.lua from nvim/lua/mate/palette.lua. Do not edit.")
line("")
line("[colors.primary]")
line(('background = "%s"'):format(c.bg))
line(('foreground = "%s"'):format(c.fg))
line(('bright_foreground = "%s"'):format(c.fg_bright))
line("")
line("[colors.cursor]")
line(('cursor = "%s"'):format(c.fg))
line(('text = "%s"'):format(c.bg))
line("")
line("[colors.vi_mode_cursor]")
line(('cursor = "%s"'):format(c.keyword))
line(('text = "%s"'):format(c.bg))
line("")
line("[colors.selection]")
line(('background = "%s"'):format(c.selection))
line('text = "CellForeground"')
line("")
line("[colors.search.matches]")
line(('background = "%s"'):format(c.warning))
line(('foreground = "%s"'):format(c.bg))
line("")
line("[colors.search.focused_match]")
line(('background = "%s"'):format(c.keyword))
line(('foreground = "%s"'):format(c.bg))
line("")
line("[colors.hints.start]")
line(('background = "%s"'):format(c.keyword))
line(('foreground = "%s"'):format(c.bg))
line("")
line("[colors.hints.end]")
line(('background = "%s"'):format(c.surface))
line(('foreground = "%s"'):format(c.fg))
line("")
line("[colors.footer_bar]")
line(('background = "%s"'):format(c.bg_alt))
line(('foreground = "%s"'):format(c.silver))
line("")
line("[colors.line_indicator]")
line(('background = "%s"'):format(c.bg_alt))
line(('foreground = "%s"'):format(c.silver))
line("")
line("[colors.normal]")
for i, n in ipairs(names) do
  line(('%s = "%s"'):format(n, ansi[i - 1]))
end
line("")
line("[colors.bright]")
for i, n in ipairs(names) do
  line(('%s = "%s"'):format(n, ansi[i + 7]))
end
local keys = vim.tbl_keys(idx)
table.sort(keys)
for _, i in ipairs(keys) do
  line("")
  line("[[colors.indexed_colors]]")
  line(("index = %d"):format(i))
  line(('color = "%s"'):format(idx[i]))
end
line("")

local path = root .. "/alacritty/mate.toml"
vim.fn.mkdir(vim.fs.dirname(path), "p")
local fh = assert(io.open(path, "w"))
fh:write(table.concat(out, "\n"))
fh:close()
io.write("wrote " .. path .. "\n\n")

-- herdr has no import; the block is pasted into herdr/config.toml by hand.
local herdr = {
  { "panel_bg", c.bg }, { "sidebar_bg", c.bg }, { "surface_dim", c.bg },
  { "surface0", c.bg_soft }, { "surface1", c.surface },
  { "overlay0", c.selection }, { "overlay1", c.border },
  { "active_row_bg", c.bg_soft }, { "selection_bg", c.surface },
  { "text", c.fg }, { "subtext0", c.grey_light },
  { "accent", c.info }, { "blue", c.func }, { "mauve", c.type }, { "teal", c.teal },
  { "green", c.string }, { "yellow", c.warning }, { "red", c.error }, { "peach", c.signal },
}
io.write("[theme.custom]  # herdr/config.toml\n")
for _, kv in ipairs(herdr) do
  io.write(('%-13s = "%s"\n'):format(kv[1], kv[2]))
end
