return {
  "nvim-neo-tree/neo-tree.nvim",
  branch = "v3.x",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "nvim-tree/nvim-web-devicons",
    "MunifTanjim/nui.nvim",
  },
  cmd = "Neotree",
  keys = {
    { "<leader>e",  "<cmd>Neotree toggle<CR>",     desc = "Toggle Neo-tree" },
    { "<leader>EF", "<cmd>Neotree filesystem<CR>", desc = "Neo-tree: Filesystem" },
    { "<leader>EB", "<cmd>Neotree buffers<CR>",    desc = "Neo-tree: Buffers" },
    { "<leader>EG", "<cmd>Neotree git_status<CR>", desc = "Neo-tree: Git status" },
  },
  opts = {
    close_if_last_window = true,
    enable_git_status = true,
    enable_diagnostics = true,
    source_selector = {
      winbar = true,
      statusline = false,
      content_layout = "start",
      tabs_layout = "start",
      padding = 0,
      separator = " ",
      separator_active = " ",
      show_separator_on_edge = false,
      sources = {
        { source = "filesystem", display_name = " File Explorer" },
        -- { source = "buffers", display_name = " Buffs" },
        { source = "git_status", display_name = " Git" },
      },
    },
    filesystem = {
      follow_current_file = { enabled = true },
      hijack_netrw_behavior = "open_current",
      use_libuv_file_watcher = true,
      group_empty_dirs = false,
      bind_to_cwd = true,
      window = {
        mappings = {
          ["<space>"] = "none",
          ["l"] = "open",
          ["h"] = "close_node",
          ["v"] = "open_vsplit",
          ["s"] = "open_split",
          ["t"] = "open_tabnew",
          ["R"] = "refresh",
          ["H"] = "toggle_hidden",
          ["Y"] = "copy_to_clipboard",
          ["P"] = "paste_from_clipboard",
        },
      },
      filtered_items = {
        visible = true,
        hide_dotfiles = false,
        hide_gitignored = false,
      },
    },
    window = {
      position = "left",
      width = 34,
      winhighlight =
      "Normal:NeoTreeNormal,NormalNC:NeoTreeNormalNC,EndOfBuffer:NeoTreeNormal,WinSeparator:NeoTreeWinSeparator",
      mappings = {
        ["<esc>"] = "close_window",
        ["?"] = "show_help",
      },
    },
    default_component_configs = {
      indent = {
        with_markers = true,
        indent_size = 2,
        padding = 1,
        marker = "│",
        last_marker = "└",
        expander_collapsed = "",
        expander_expanded = "",
      },
      icon = {
        folder_closed = "",
        folder_open = "",
        folder_empty = "",
        default = "󰈚",
      },
      modified = {
        symbol = "●",
      },
      git_status = {
        symbols = {
          added = "",
          modified = "",
          deleted = "",
          renamed = "󰁕",
          untracked = "",
          ignored = "",
          unstaged = "󰄱",
          staged = "",
          conflict = "",
        },
      },
    },
  },
}
