export HOMEBREW_PREFIX=/opt/homebrew
export HOMEBREW_CELLAR=/opt/homebrew/Cellar
export HOMEBREW_REPOSITORY=/opt/homebrew
export INFOPATH=/opt/homebrew/share/info${INFOPATH:+:$INFOPATH}

export LANG=en_US.UTF-8
export EDITOR=nvim
export VISUAL=nvim

export GOPATH="$HOME/Develop/go"
export GOPRIVATE=github.com/nhnvrr

typeset -U path PATH
path=(
  "$GOPATH/bin"
  /opt/homebrew/{bin,sbin}
  /opt/homebrew/opt/libpq/bin
  "$HOME/.bun/bin"
  "$HOME/.local/bin"
  /usr/local/bin
  $path
)
